### ISSUE TITLE
Not able to route messages from child device's module to parent device's module

### ISSUE THREAD

**Issue by manupradeep2000** [Azure-Samples/iot-edge-for-iiot#26]
I am able to setup child device and parent device and able to deploy modules in both the devices, but I want to collect all the messages from child device's module by a custom developed parent device's module. There is no routing facility using which I can route all messages from child-device's module to parent-device's module. Routing messages from child device using the keyword "$upstream" is sending the messages directly to cloud-iothub. I need to do some operation at parent-device module before sending it to cloud-iothub. Please let me know if it is possible/technical limitation to route messages from a module running at child device to another module running in parent device using nested edge.

**Comment by ebertrams** [comment]
Hi @manupradeep2000 sorry for the late replied, we've since then updated since sample with an example of a route that does that, see this line: https://github.com/Azure-Samples/iot-edge-for-iiot/blob/eb9438ad7c8e1c18f7cf8d23d7bfa92882c7366a/offline-dashboards/dashboard.layered.deployment.template.json#L31

I m thus going to close this issue. Please reopen if you still have some issue / further question.

Thanks,
Emmanuel
